package com.example.pandatv.been;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.pandatv.been.AllData;
import com.example.pandatv.been.TabData;
import com.example.pandatv.been.UserBeen;

import com.example.pandatv.been.AllDataDao;
import com.example.pandatv.been.TabDataDao;
import com.example.pandatv.been.UserBeenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig allDataDaoConfig;
    private final DaoConfig tabDataDaoConfig;
    private final DaoConfig userBeenDaoConfig;

    private final AllDataDao allDataDao;
    private final TabDataDao tabDataDao;
    private final UserBeenDao userBeenDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        allDataDaoConfig = daoConfigMap.get(AllDataDao.class).clone();
        allDataDaoConfig.initIdentityScope(type);

        tabDataDaoConfig = daoConfigMap.get(TabDataDao.class).clone();
        tabDataDaoConfig.initIdentityScope(type);

        userBeenDaoConfig = daoConfigMap.get(UserBeenDao.class).clone();
        userBeenDaoConfig.initIdentityScope(type);

        allDataDao = new AllDataDao(allDataDaoConfig, this);
        tabDataDao = new TabDataDao(tabDataDaoConfig, this);
        userBeenDao = new UserBeenDao(userBeenDaoConfig, this);

        registerDao(AllData.class, allDataDao);
        registerDao(TabData.class, tabDataDao);
        registerDao(UserBeen.class, userBeenDao);
    }
    
    public void clear() {
        allDataDaoConfig.clearIdentityScope();
        tabDataDaoConfig.clearIdentityScope();
        userBeenDaoConfig.clearIdentityScope();
    }

    public AllDataDao getAllDataDao() {
        return allDataDao;
    }

    public TabDataDao getTabDataDao() {
        return tabDataDao;
    }

    public UserBeenDao getUserBeenDao() {
        return userBeenDao;
    }

}
